include:
- ./functions/getaccidents.zip
kind: ArchiveUploadSpec
name: functions-getaccidents-zip-rHek

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getaccidents
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-getaccidents-zip-rHek
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-05T06:00:30Z"
