include:
- ./functions/storeweather.zip
kind: ArchiveUploadSpec
name: functions-storeweather-zip-HriS

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: storeweather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-storeweather-zip-HriS
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-05T06:00:41Z"
