include:
- ./functions/getroadcondition.zip
kind: ArchiveUploadSpec
name: functions-getroadcondition-zip-ShUK

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getroadcondition
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-getroadcondition-zip-ShUK
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-05T06:03:10Z"
