apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: searchweatherdates
spec:
  createingress: false
  functionref:
    functionweights: null
    name: searchweather
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /searchweather/{StartDate}/{EndDate}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /searchweather/{StartDate}/{EndDate}
