apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getaccidents
spec:
  createingress: true
  functionref:
    functionweights: null
    name: getaccidents
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /getaccidents
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /getaccidents
