apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: storeweather
spec:
  createingress: true
  functionref:
    functionweights: null
    name: storeweather
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /storeweather
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /storeweather
